# Site settings
title: Stripstarter
email: stripstarter@gmail.com
description: "Social crowdsourcing."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stripstarter.dev" # the base hostname & protocol for your site
twitter_username: stripstarter
github_username:  stripstarter

# Build settings
markdown: kramdown
